
// Login Query
module.exports.checkUser = 'select * from KEYSTORE where BHAMASHAH_ID=:BHAMASHAH_ID AND MEMBERID=:MEMBERID AND SSO_ID=:SSO_ID'
module.exports.newuser = 'insert into KEYSTORE (BHAMASHAH_ID, MEMBERID, SSO_ID, EHRID, DISTRICT, RECORD_COUNT,HOSPITAL_RECORDS_COUNT,STATUS) values(:BHAMASHAH_ID, :MEMBERID, :SSO_ID, :EHRID, :DISTRICT, :COUNT, :HOSPITAL_RECORD_COUNT,:STATUS )'
module.exports.marriage = 'select * from KEYSTORE where SSO_ID=:SSO_ID and SSO_ID IS NOT NULL'
module.exports.updateMarriagedUser = 'update KEYSTORE set BHAMASHAH_ID=:BHAMASHAH_ID,MEMBERID=:MEMBERID,STATUS=:STATUS where SSO_ID=:SSO_ID and SSO_ID IS NOT NULL'
module.exports.died = 'select * from KEYSTORE where BHAMASHAH_ID=:BHAMASHAH_ID AND SSO_ID=:SSO_ID AND SSO_ID IS NOT NULL'
module.exports.updateDeadUser = 'update KEYSTORE set MEMBERID=:MEMBERID where BHAMASHAH_ID=:BHAMASHAH_ID AND SSO_ID=:SSO_ID AND SSO_ID IS NOT NULL '
module.exports.migration = 'select * from KEYSTORE where BHAMASHAH_ID=:BHAMASHAH_ID AND MEMBERID=:MEMBERID'
module.exports.updateUser = 'update KEYSTORE set SSO_ID=:SSO_ID where BHAMASHAH_ID=:BHAMASHAH_ID AND MEMBERID=:MEMBERID AND SSO_ID IS NULL'


//Dashboard Query
module.exports.loginCount = 'update KEYSTORE set RECORD_COUNT=RECORD_COUNT+1 where EHRID=:EHRID'

// module.exports.readSuccessCount = 'UPDATE WIDGET_COUNT SET SUCCESS_COUNT = SUCCESS_COUNT + 1, READ_COUNT = READ_COUNT + 1, TOTAL_COUNT = TOTAL_COUNT + 1 WHERE WIDGET_NAME=:WIDGETNAME'
// module.exports.readFailureCount = 'UPDATE WIDGET_COUNT SET FAILURE_COUNT = FAILURE_COUNT + 1, READ_COUNT = READ_COUNT + 1, TOTAL_COUNT = TOTAL_COUNT + 1 WHERE WIDGET_NAME=:WIDGETNAME'
// module.exports.addSuccessCount = 'UPDATE WIDGET_COUNT SET SUCCESS_COUNT = SUCCESS_COUNT + 1, CREATE_COUNT = CREATE_COUNT + 1, TOTAL_COUNT = TOTAL_COUNT + 1 WHERE WIDGET_NAME=:WIDGETNAME'
// module.exports.addFailureCount = 'UPDATE WIDGET_COUNT SET FAILURE_COUNT = FAILURE_COUNT + 1, CREATE_COUNT = CREATE_COUNT + 1, TOTAL_COUNT = TOTAL_COUNT + 1 WHERE WIDGET_NAME=:WIDGETNAME'
// module.exports.updateSuccessCount = 'UPDATE WIDGET_COUNT SET SUCCESS_COUNT = SUCCESS_COUNT + 1, UPDATE_COUNT = UPDATE_COUNT + 1, TOTAL_COUNT = TOTAL_COUNT + 1 WHERE WIDGET_NAME=:WIDGETNAME'
// module.exports.updateFailureCount = 'UPDATE WIDGET_COUNT SET FAILURE_COUNT = FAILURE_COUNT + 1, UPDATE_COUNT = UPDATE_COUNT + 1, TOTAL_COUNT = TOTAL_COUNT + 1 WHERE WIDGET_NAME=:WIDGETNAME'
// module.exports.deleteSuccessCount = 'UPDATE WIDGET_COUNT SET SUCCESS_COUNT = SUCCESS_COUNT + 1, DELETE_COUNT = DELETE_COUNT + 1, TOTAL_COUNT = TOTAL_COUNT + 1 WHERE WIDGET_NAME=:WIDGETNAME'
// module.exports.deleteFailureCount = 'UPDATE WIDGET_COUNT SET FAILURE_COUNT = FAILURE_COUNT + 1, DELETE_COUNT = DELETE_COUNT + 1, TOTAL_COUNT = TOTAL_COUNT + 1 WHERE WIDGET_NAME=:WIDGETNAME'
// module.exports.summarySuccessCount = 'UPDATE WIDGET_COUNT SET SUCCESS_COUNT = SUCCESS_COUNT + 1, SUMMARY_COUNT = SUMMARY_COUNT + 1, TOTAL_COUNT = TOTAL_COUNT + 1 WHERE WIDGET_NAME=:WIDGETNAME'
// module.exports.summaryFailureCount = 'UPDATE WIDGET_COUNT SET FAILURE_COUNT = FAILURE_COUNT + 1, SUMMARY_COUNT = SUMMARY_COUNT + 1, TOTAL_COUNT = TOTAL_COUNT + 1 WHERE WIDGET_NAME=:WIDGETNAME'

//Device counts
module.exports.deviceCount = 'UPDATE DEVICES_COUNT SET DEVICE_COUNT = DEVICE_COUNT + 1 where DEVICES = :DEVICES'
//APITIMING QUERIES
module.exports.addAPIs = 'update TIME_TAKEN_BY_APIS set ADD_API=:ADD_API where WIDGET_NAME=:WIDGETNAME'
module.exports.readAPIs = 'update TIME_TAKEN_BY_APIS set READ_API=:READ_API where WIDGET_NAME=:WIDGETNAME'
module.exports.updateAPIs = 'update TIME_TAKEN_BY_APIS set UPDATE_API=:UPDATE_API where WIDGET_NAME=:WIDGETNAME'
module.exports.delateAPIs = 'update TIME_TAKEN_BY_APIS set DELETE_API=:DELETE_API where WIDGET_NAME=:WIDGETNAME'
module.exports.summaryAPIs = 'update TIME_TAKEN_BY_APIS set SUMMARY_API=:SUMMARY_API where WIDGET_NAME=:WIDGETNAME'

//ADD MEMBERS

module.exports.checkFamilyMembers = 'select * from KEYSTORE where BHAMASHAH_ID=:BHAMASHAH_ID AND MEMBERID=:MEMBERID'
module.exports.addFamilyMember = 'insert into KEYSTORE (BHAMASHAH_ID, MEMBERID, SSO_ID, EHRID,HOSPITAL_RECORDS_COUNT,STATUS) values(:BHAMASHAH_ID, :MEMBERID, :SSO_ID, :EHRID,:HOSPITAL_RECORDS_COUNT,:STATUS)'
module.exports.getMemberIds = 'select MEMBERID from KEYSTORE where BHAMASHAH_ID=:BHAMASHAH_ID AND STATUS=:STATUS'
module.exports.statusChange = 'UPDATE KEYSTORE SET STATUS = :STATUS where BHAMASHAH_ID = :BHAMASHAH_ID AND MEMBERID = :MEMBERID',



    module.exports.addSuccessCount = 'UPDATE APIS_COUNTS SET ADD_API_S = ADD_API_S + 1 WHERE WIDGET_NAME=:WIDGETNAME',
    module.exports.addFailureCount = 'UPDATE APIS_COUNTS SET ADD_API_F = ADD_API_F + 1 WHERE WIDGET_NAME=:WIDGETNAME',
    module.exports.readSuccessCount = 'UPDATE APIS_COUNTS SET READ_API_S = READ_API_S + 1 WHERE WIDGET_NAME=:WIDGETNAME'
module.exports.readFailureCount = 'UPDATE APIS_COUNTS SET READ_API_F = READ_API_F + 1 WHERE WIDGET_NAME=:WIDGETNAME'
module.exports.updateSuccessCount = 'UPDATE APIS_COUNTS SET UPDATE_API_S = UPDATE_API_S + 1 WHERE WIDGET_NAME=:WIDGETNAME'
module.exports.updateFailureCount = 'UPDATE APIS_COUNTS SET UPDATE_API_F = UPDATE_API_F + 1 WHERE WIDGET_NAME=:WIDGETNAME'
module.exports.deleteSuccessCount = 'UPDATE APIS_COUNTS SET DELETE_API_S = DELETE_API_S + 1 WHERE WIDGET_NAME=:WIDGETNAME'
module.exports.deleteFailureCount = 'UPDATE APIS_COUNTS SET DELETE_API_F = DELETE_API_F + 1 WHERE WIDGET_NAME=:WIDGETNAME'
module.exports.summarySuccessCount = 'UPDATE APIS_COUNTS SET SUMMARY_API_S = SUMMARY_API_S + 1 WHERE WIDGET_NAME=:WIDGETNAME'
module.exports.summaryFailureCount = 'UPDATE APIS_COUNTS SET SUMMARY_API_F = SUMMARY_API_F + 1 WHERE WIDGET_NAME=:WIDGETNAME'


